### PR TITLE
Added 'Truffle: ' prefix to deploy and build

### PR DESCRIPTION
**Pull request by NikolaiSch**
Fix for #72

### CODE REVIEW

**Comment by kevinbluer** [comment]
Awesome, thanks @NikolaiSch! Will get this review / merged shortly 🥳

**Comment by NikolaiSch** [comment]
> Awesome, thanks @NikolaiSch! Will get this reviewed / merged shortly 🥳

Apologies, gonna upload a fix, a couple of tests fail!

**Comment by NikolaiSch** [comment]
tests pass now, just required a yarn cache clear and then it worked

**Comment by NikolaiSch** [comment]
@kevinbluer any updates on the review?

**Comment by kevinbluer** [comment]
Hey @NikolaiSch, thanks for the nudge and absolutely...we've just been getting things finalized for the `v2.3` release (which this will be going out in too) so will be getting it merged shortly, most likely early next week. Thanks again for it! cc @michaeljohnbennett @xhulz

**Comment by kevinbluer** [comment]
Actually quick request if possible @NikolaiSch, would you mind adding a quick commit that removes the `yarn.lock`?

**Comment by NikolaiSch** [comment]
@kevinbluer of course, doing now!

**Review by kevinbluer — APPROVED** [review]
Thanks again @NikolaiSch 🙌

**Comment by kevinbluer** [comment]
Hey @NikolaiSch now merged 👍  Let me know if you'd like to look into another feature...more than happy to give you some suggestions if you're interested. Thanks again!

**Comment by NikolaiSch** [comment]
@kevinbluer, yep, any other issues, just mention me :)

**Pull request merged**
