### PR TITLE
Add support for multiple Truffle config files

### LINKED ISSUE #92: Add support for multiple truffle config files (e.g. truffle-config.ovm.js)
More detail to follow 🤝

### PR DESCRIPTION
**Pull request by acuarica**
Closes #92.

### CODE REVIEW

**Comment by kevinbluer** [comment]
nice one @acuarica! will take a look at this tomorrow.

**Review by xhulz — APPROVED** [review]
LGTM!

**Comment by xhulz** [comment]
Hey @acuarica, I have a question regarding the workflow:

I'm attempting to deploy the contracts, and when I choose 'truffle-config.js,' the QuickPick list with the networks loads successfully. However, if I choose 'truffle-config.ovm.js,' the networks list does not reflect the networks included within this configuration file. Instead, the QuickPick displays the 'tuffle-config.js' networks list.

Shouldn't we display the list from the second configuration file?

Cheers!

optmism-1659086230207

**Comment by acuarica** [comment]
Totally!

I did an initial implementation to check whether this might work. More importantly, we need to figure out how to solve point **2** from https://github.com/trufflesuite/vscode-ext/issues/92#issuecomment-1198686225:

> Where the Contract Explorer and Deployments should take the data from? In this scenario, i.e., multiple workspaces or multiple config files, they could add a top level item that represents the Truffle config file it was taken from.

**Review by michaeljohnbennett — APPROVED** [review]
LGTM 👍🏻

**Comment by michaeljohnbennett** [comment]
> Totally!
> 
> I did an initial implementation to check whether this might work. More importantly, we need to figure out how to solve point **2** from [#92 (comment)](https://github.com/trufflesuite/vscode-ext/issues/92#issuecomment-1198686225):
> 
> > Where the Contract Explorer and Deployments should take the data from? In this scenario, i.e., multiple workspaces or multiple config files, they could add a top level item that represents the Truffle config file it was taken from.

This is hard to decide if you have monorepo's or other hierarchies, where the networks come from, and how they are shown/restricted/filtered etc. 

Do you restrict the networks to only contracts in or below that config files folder? Or globally? If the latter, isn't it possible to inadvertently deploy contracts in other folders to a network not made for it? Say you have an L1 project and a L2 project under your main repo, how does that work out? I realise these are contrived (somewhat) examples but the logic at least needs to be decided how we handle this. The code overall so far, to retrieve looks fine, I guess the detail of how this is presented and then used by the user is the main thing I want to get clear.

**Comment by acuarica** [comment]
Besides supporting multiple Truffle config files, this PR introduces some other changes, most notably:

- **Make `Entry` in `src/views/FileExplorer.ts` compatible with other commands.** See the TS docs for `Entry` for a detail explanation.
- **Use `registerCommand` local function in `extension.ts`.** This is to avoid creating a local variable just to be included in the `context.subscriptions` array.
- **Use `@/` when `import`ing.** This is to avoid `import` statements to use relative paths.
- **Fix `getTruffleWorkspace` mock typing in tests.** Using precise types for mocks, _e.g._, `SinonStub<...>` helps to identify broken usages due to signature changes.

**Review by xhulz — COMMENTED** [review]
Hey @acuarica,

Thanks for this PR :)

Overall, LGTM!

I did some tests and i've got some different behaviors:

**Create a new contract:** 
- Mac OS:
optmism-1659523374732

- Windows
https://user-images.githubusercontent.com/32708942/182598404-d2aa923c-6c3e-4882-a72e-551f8291e0c9.mov


**More than 1 truffle configuration file:**

- Mac OS & Windows
optmism-1659524329082


**Contract Explorer "+" symbol (create a new contract):**

-Mac & Windows
optmism-1659525586550

I've tested Compile & Deploy and working fine

Thank you :)

**Comment by acuarica** [comment]
Hi @xhulz, many thanks for the feedback. I wasn't sure if I should fix `Create Contract` command, since this PR is already quite big. That issue is related to a hardcoded `contracts` path.

As for the multiple Truffle config files, would you mind to rename `truffle-config-test.js` to `truffle-config.test.js` (changing dash for dot) and try again? Currently the glob pattern to match Truffle config files is `truffle-config{,.*}.js`. Maybe we should make this explicit somehow, any ideas?

**Comment by xhulz** [comment]
Hey @acuarica,

Ok, maybe it would be better to raise a new issue for the "Create new Contract" command, just to avoid polluting this PR.

Regarding the Truffle config files, it's working with "." instead "-".

Thank you :)

**Comment by acuarica** [comment]
> Ok, maybe it would be better to raise a new issue for the "Create new Contract" command, just to avoid polluting this PR.

Sounds good. Once this is merged, I'll take care of the `Create Contract` command. I'll open an issue for this.

> Regarding the Truffle config files, it's working with "." instead "-".

Good to hear! I've changed the placeholder of the quick pick, so at least it's a little bit more informative https://github.com/trufflesuite/vscode-ext/pull/181/commits/81af6601e104f4f9509d832df25d9e2677e60269.

**Comment by xhulz** [comment]
Cool, thanks @acuarica!

**Review by michaeljohnbennett — APPROVED** [review]
looks ok, as I had commented before, not having tested this, how will this handle monorepos and config files, are contracts in a sub folder linked with their parent config or does this all merge up to the top level somehow?

**Comment by acuarica** [comment]
The `Contract Explorer` is not yet modified to support this. Only the `Deployments View`. The `Deployments View` adds a new top-level item when there are multiple files.

**Pull request merged**
