### PR TITLE
feat(explorer): added createContract

### PR DESCRIPTION
**Pull request by NikolaiSch**
fix(commands): fixed typo "Plataform" => "Platform"

### CODE REVIEW

**Comment by NikolaiSch** [comment]
this is in reference to issue: #105, and a clean up of pull request #113. Now with correct prettier formatting, and conventional commit messages

**Comment by NikolaiSch** [comment]
Now, it automatically refreshes the explorer after calling createContract

**Review by michaeljohnbennett — APPROVED** [review]
Looks good, thanks @NikolaiSch! 👍🏻

**Review by xhulz — APPROVED** [review]
Nice job @NikolaiSch :)

**Comment by michaeljohnbennett** [comment]
Sorry @NikolaiSch we merged in some things that had conflicts, can you fix those then I'll merge your PR in immediately or @xhulz will.

**Comment by NikolaiSch** [comment]
> Sorry @NikolaiSch we merged in some things that had conflicts, can you fix those then I'll merge your PR in immediately or @xhulz will.

i'm new to git, how would i go about doing this. sorry for late replies.

**Comment by michaeljohnbennett** [comment]
@NikolaiSch I think you just pull this upstream branch back into your personal fork. There is usually a button or dialogue at the top of your version saying the upstream repo is x commits ahead or the like.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Has some info.

**Comment by NikolaiSch** [comment]
@kevinbluer any idea on this, looks like a test is failing, on a file I havent changed. 
Screen Shot 2022-07-08 at 10 23 13

**Pull request merged**
