### PR TITLE
Add a Walkthrough on the Getting Started splash

### PR DESCRIPTION
**Pull request by acuarica**
This is the initial implementation of #51. 

Most of the text, images and features to present were taken from https://trufflesuite.com/blog/build-on-web3-with-truffle-vs-code-extension/. What else should we add to the walkthrough?

Some of the screenshots from the blog post seem outdated. I wasn't sure whether to take new screenshots, or make short videos/gifs.

The Welcome page and this Walkthrough may have some overlapping. Shall we keep both? Linking #124 since it relates to the Welcome page.

@michaeljohnbennett @xhulz @kevinbluer

### CODE REVIEW

**Comment by davidmurdoch** [comment]
Can we do webp? :-)

**Comment by michaeljohnbennett** [comment]
gonna make this a draft PR right now. 


As @kevinbluer said, this is excellent, just need a bit more thought going into this welcome page removal/rationalisation and I would love to lead with this walkthrough in app and via a getting started video. 👍🏻

**Comment by acuarica** [comment]
> gonna make this a draft PR right now.

Thanks @michaeljohnbennett.

> As @kevinbluer said, this is excellent, just need a bit more thought going into this welcome page removal/rationalisation and I would love to lead with this walkthrough in app and via a getting started video. 👍🏻

I would love to see a Walkthrough that's a complement of the `README`. As a potential user of the extension, the first thing I see when I found the extension is the `README`. Either in GitHub, the [Marketplace](https://marketplace.visualstudio.com/items?itemName=trufflesuite-csi.truffle-vscode), or VS Code itself. That's why I usually like to see in the `README` short videos showcasing its main features. The Walkthrough then should be a quick guide on how to activate those features. To sum up, we need to evaluate what value the `README`, Walkthrough and Welcome page provide to give best developer experience.

**Comment by michaeljohnbennett** [comment]
let me know when this is ready to review again or if you need any more info from me.

**Comment by acuarica** [comment]
@michaeljohnbennett @xhulz @kevinbluer please take a look. I updated some gifs/images.

Kevin, I left the welcome page for now. We can later decide if they should co-exist or we should remove the welcome page in a future PR.

**Pull request merged**
